FROM mysql:5.7.34

ENV LANG ja_JP.UTF-8
ENV MYSQL_ROOT_PASSWORD rootpass
ENV MYSQL_DATABASE 360database
ENV MYSQL_USER testuser
ENV MYSQL_PASSWORD testpass

COPY ./docker/mysql/my.conf /etc/mysql/conf.d/my.cnf